#ESTRUTURAS DE CONTROLE
#CODIGOS PARA ANALISAR DADOS E ESCOLHER QUAL CAMINHO SEGUIR
#DIVIDE-SE EM CONDICIONAL E ITERAÇÃO

#ITERAÇÃO: ESTRUTURA DE CODIGO Q GERENCIA QUANTAS VEZES O CODIGO SERÁ EXECUTADO
#TIPOS:

#FOR : USADO PARA PERCORRER UMA COLEÇÃO DE ELEMENTOS
#TIMES : EXECUTA UMA REPETIÇÃO POR DETERMINADO NUMERO DE VEZES
#WHILE : INSTRUÇÃO Q REPETE UM CODIGO ENQUANTO SUA CONDIÇÃO É VERDADEIRA
#DO/WHILE - LOOP: ELE CRIA UM LAÇO DE REPETIÇÃO QUE SÓ É PARADO QUANDO UMA INSTRUÇÃO BREAK for verdadeira
